[build-system]
requires = [
  "setuptools>=45",
  "wheel",
  "setuptools_scm[toml]>=6.2",
  "oldest-supported-numpy",
  "Cython>=0.29.24"
]

[tool.black]
target-version = ['py38', 'py39', 'py310']
exclude = '''
(
    \.egg
  | \.git
  | \.mypy_cache
  | \.oytest_cache
  | _build
  | buck-out
  | build
  | dist
)
'''

[tool.setuptools_scm]
write_to = "linearmodels/_version.py"
